version: '3.1'
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    user: 1000:1000
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./src:/var/www/html
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini 
  db:
    image: mariadb:latest
    restart: no
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
  db_admin:
    image: phpmyadmin/phpmyadmin
    restart: no
    ports:
      - 8181:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: examplepass
  smtp:
    image: mailhog/mailhog
    restart: no
    ports:
      - 8025:8025
    logging:
      driver: "none"
volumes:
  db: